name: Version Release


# NOTE: not tested, working with flags starting with "r" (e.g. r1.0.0)
on:
  push:
    tags:
      - 'r*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Start
      run: |
        echo Start

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.5'

      - name: Install Zip
        run: |
          apt-get update
          apt-get install -y zip

      - name: Check out code
        uses: actions/checkout@v4

      - name: Build and Zip Binaries
        run: |
          GOOS=linux GOARCH=amd64 go build -o data_listener_linux_amd64 src/cmd/main.go
          zip data_listener_${GITHUB_REF_NAME#v}_linux_amd64.zip data_listener_linux-amd64 datalistener/README.md datalistener/config.toml datalistener/examples datalistener/https

          GOOS=darwin GOARCH=amd64 go build -o data_listener_darwin_amd64 src/cmd/main.go
          zip data_listener_${GITHUB_REF_NAME#v}_darwin_amd64.zip data_listener_darwin_amd64 datalistener/README.md datalistener/config.toml datalistener/examples datalistener/https

          GOOS=windows GOARCH=amd64 go build -o data_listener_windows_amd64.exe src/cmd/main.go
          zip data_listener_${GITHUB_REF_NAME#v}_windows_amd64.zip data_listener_windows_amd64.exe datalistener/README.md datalistener/config.toml datalistener/examples datalistener/https

      - name: Use Gitea Release Action
        uses: https://gitea.com/actions/release-action@main
        with:
          files: |
            data_listener_${GITHUB_REF_NAME#v}_linux_amd64.zip
            data_listener_${GITHUB_REF_NAME#v}_darwin_amd64.zip
            data_listener_${GITHUB_REF_NAME#v}_windows_amd64.zip
          api_key: '${{secrets.RELEASE_TOKEN}}'