name: Version Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20.5'

    - name: Install Zip
      run: |
        apt-get update
        apt-get install -y zip        


    - name: Check out code
      uses: actions/checkout@v4
      
    - name: Build Binaries
      run: |
        GOOS=linux GOARCH=amd64 go build -o data_listener_linux-amd64 datalistener/src/cmd/main.go
        GOOS=darwin GOARCH=amd64 go build -o data_listener_darwin_amd64 datalistener/src/cmd/main.go      
        GOOS=windows GOARCH=amd64 go build -o data_listener_windows_amd64.exe datalistener/src/cmd/main.go
    - name: Make Zip files
      run: |
        zip data_listener_linux_amd64.zip data_listener_linux-amd64 datalistener/README.md datalistener/config.toml datalistener/examples datalistener/https    
        zip data_listener_darwin_amd64.zip data_listener_darwin_amd64 datalistener/README.md datalistener/config.toml datalistener/examples datalistener/https
        zip data_listener_windows_amd64.zip data_listener_windows_amd64.exe datalistener/README.md datalistener/config.toml datalistener/examples datalistener/https


    - name: Use Gitea Release Action
      uses: https://gitea.com/actions/release-action@main
      with:
        files: |
          data_listener_linux_amd64.zip
          data_listener_darwin_amd64.zip
          data_listener_windows_amd64.zip          
        api_key: '${{secrets.RELEASE_TOKEN}}'